# Site settings
title: Pica Pottery
description: 'A Micropottery in Boulder, Colorado, USA'
url: 'http://picapottery.com'
baseurl: ''
profilepic: '/images/logo-white.png'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '4ce6458bb7.js'
insta_username: picapottery
email: hello@picapottery.com
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md','LICENSE']
